### ISSUE TITLE
Glyphs of group messaging systems not centered

### ISSUE THREAD

**Issue by dschulten** [comsysto/enterprise-integration-pattern-shapes-for-gliffy#2]
The square region around the glyphs in the group messaging-systems (the one where arrows can be attached) is not centered around the images, but it is outside of the image to the lower right. Does not happen initially, but only  after repeated editing of a chart in Gliffy.

Seen with the messeage-translator glyph and others.

Reimporting the group fixes it once. When editing next time, the problem is back.

**Comment by clouless** [comment]
thx for the notice, I will investigate it the next days.
But it really sounds like a gliphy bug. But I will try to reproduce it.

**Comment by clouless** [comment]
So for me this is working. Arrows stay attached to shapes.

![image](https://user-images.githubusercontent.com/12599965/47736804-c5a1dc80-dc6f-11e8-82f7-ef7a6b6ebd7e.png)

Please open a Bug at Gliffy if this happens for you. (I am having an older version of Gliffy: 7.0.2)
